name: Deploy Flask App to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create PEM file
        run: |
          echo "${{ secrets.dharshan }}" > key.pem
          chmod 400 key.pem

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem app.py ubuntu@13.127.223.69:/home/ubuntu/
          scp -o StrictHostKeyChecking=no -i key.pem requirements.txt ubuntu@13.127.223.69:/home/ubuntu/

      - name: Run application on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.127.223.69 << 'EOF'
            cd /home/ubuntu
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pkill -f app.py || true
            nohup python3 app.py > output.log 2>&1 &
          EOF
